<h1>Task 1</h1>

In [24]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [25]:
df=pd.read_csv('Task 1 Data set/cleaned_data.csv')

In [26]:
df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month,EDUCATION_CAT,graduate school,high school,others,university
0,798fc410-45c1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,1,university,0,0,0,1
1,8a8c8f3b-8eb4,120000,2,2,2,26,-1,2,0,0,...,1000,1000,0,2000,1,university,0,0,0,1
2,85698822-43f5,90000,2,2,2,34,0,0,0,0,...,1000,1000,1000,5000,0,university,0,0,0,1
3,0737c11b-be42,50000,2,2,1,37,0,0,0,0,...,1200,1100,1069,1000,0,university,0,0,0,1
4,3b7f77cc-dbc0,50000,1,2,1,57,-1,0,-1,0,...,10000,9000,689,679,0,university,0,0,0,1
5,ceae2946-47e4,50000,1,1,2,37,0,0,0,0,...,657,1000,1000,800,0,graduate school,1,0,0,0
6,d3b8ce26-9c89,500000,1,1,2,29,0,0,0,0,...,38000,20239,13750,13770,0,graduate school,1,0,0,0
7,d6e1911b-54d0,100000,2,2,2,23,0,-1,-1,0,...,0,581,1687,1542,0,university,0,0,0,1
8,8421d3b3-2b54,140000,2,3,1,28,0,0,2,0,...,432,1000,1000,1000,0,high school,0,1,0,0
9,62a2fd79-cd90,20000,1,3,2,35,-2,-2,-2,-2,...,0,13007,1122,0,0,high school,0,1,0,0
10,b73c34fc-91cf,200000,2,3,2,34,0,0,2,0,...,50,300,3738,66,0,high school,0,1,0,0
11,4777689a-5131,260000,2,1,2,51,-1,-1,-1,-1,...,8583,22301,0,3640,0,graduate school,1,0,0,0
12,b814ac5c-3d88,630000,2,2,2,41,-1,0,-1,-1,...,6500,6500,2870,0,0,university,0,0,0,1
13,a17b23d4-357b,70000,1,2,2,30,1,2,2,0,...,3000,3000,1500,0,1,university,0,0,0,1
14,0d6f99ad-84e9,250000,1,1,2,29,0,0,0,0,...,3000,3000,3000,3000,0,graduate school,1,0,0,0
15,8f023df0-a9ea,50000,2,3,3,23,1,2,0,0,...,1100,1200,1300,1100,0,high school,0,1,0,0
16,cbf648a6-98aa,20000,1,1,2,24,0,0,2,2,...,1500,0,1650,0,1,graduate school,1,0,0,0
17,cb258690-8ea2,360000,2,1,1,49,1,-2,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
18,f6f0307a-b75f,180000,2,1,2,29,1,-2,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
19,47a4cdaa-aa20,130000,2,3,2,39,0,0,0,0,...,1000,2000,930,33764,0,high school,0,1,0,0
20,834b2cac-750e,120000,2,2,1,39,-1,-1,-1,-1,...,0,632,316,0,1,university,0,0,0,1
21,c1d1d0f2-6aec,70000,2,2,2,26,2,0,0,2,...,0,3601,0,1820,1,university,0,0,0,1
22,66a293d5-6384,450000,2,1,1,40,-2,-2,-2,-2,...,560,0,0,1128,1,graduate school,1,0,0,0
23,817396f7-aad1,90000,1,1,2,23,0,0,0,-1,...,5398,1200,2045,2000,0,graduate school,1,0,0,0
24,275d9f10-f748,50000,1,3,2,23,0,0,0,0,...,1001,1432,1062,997,0,high school,0,1,0,0
25,7784e5a8-a66c,60000,1,1,2,27,1,-2,-1,-1,...,0,500,0,1000,1,graduate school,1,0,0,0
26,99ccbfaa-715b,50000,2,3,2,30,0,0,0,0,...,1000,1500,1000,1012,0,high school,0,1,0,0
27,72c682a7-c8af,230000,2,1,2,27,-1,-1,-1,-1,...,15339,14307,37292,0,0,graduate school,1,0,0,0
28,a8eb0be8-23bb,50000,1,2,2,33,2,0,0,0,...,1000,1000,1000,716,1,university,0,0,0,1
29,3b76b111-03c1,100000,1,1,2,32,0,0,0,0,...,3302,3204,3200,2504,0,graduate school,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26634,22a584bc-ac83,150000,1,4,2,31,2,0,0,0,...,0,0,0,0,1,others,0,0,1,0
26635,db2acf78-7f5d,20000,1,2,2,34,0,0,0,0,...,1000,5000,12914,600,0,university,0,0,0,1
26636,0b4f798d-f993,200000,1,2,1,33,0,0,0,0,...,2059,3000,9751,3000,0,university,0,0,0,1
26637,af452e9d-d287,360000,1,1,1,34,-1,-1,-1,0,...,8907,53,19584,16080,0,graduate school,1,0,0,0
26638,a381d0b4-087a,80000,1,3,1,36,0,0,0,0,...,2530,2556,3700,3000,0,high school,0,1,0,0
26639,a40d8b62-0083,190000,1,1,1,37,0,0,0,0,...,25128,10115,148482,4800,0,graduate school,1,0,0,0
26640,acdb424a-32bd,50000,1,2,1,37,1,2,2,2,...,0,0,1000,1000,1,university,0,0,0,1
26641,8dea83fa-2f50,40000,1,2,2,47,2,2,3,2,...,2000,0,3520,0,1,university,0,0,0,1
26642,f2df66b1-ef3b,420000,1,1,2,34,0,0,0,0,...,5500,5500,5600,5000,0,graduate school,1,0,0,0
26643,6c7190e2-b3fe,310000,1,2,1,39,0,0,0,0,...,10029,8049,8040,10059,0,university,0,0,0,1
26644,239a1d2e-f4f4,180000,1,1,1,32,-2,-2,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
26645,2623fe20-6010,50000,1,3,2,42,0,0,0,0,...,5000,3000,4500,2000,0,high school,0,1,0,0
26646,af84788c-4c27,50000,1,2,1,44,1,2,2,2,...,0,517,503,585,0,university,0,0,0,1
26647,207df2a7-7dd6,90000,1,2,1,36,0,0,0,0,...,1500,1200,2500,0,1,university,0,0,0,1
26648,429d2c82-67ae,20000,1,2,1,44,-2,-2,-2,-2,...,2890,9263,1824,1701,0,university,0,0,0,1
26649,71ccca61-6306,240000,1,1,2,30,-2,-2,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
26650,39b25a8c-193b,360000,1,1,2,35,-1,-1,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
26651,aaf9f747-0646,130000,1,1,2,34,0,0,0,0,...,93000,4000,5027,4005,0,graduate school,1,0,0,0
26652,ef8a4bcd-79f3,250000,1,1,1,34,0,0,0,0,...,9011,6000,7000,6009,0,graduate school,1,0,0,0
26653,87388419-6a89,150000,1,1,2,35,-1,-1,-1,-1,...,783,0,0,0,0,graduate school,1,0,0,0
26654,33170a20-8592,140000,1,2,1,41,0,0,0,0,...,4228,1505,2000,2000,0,university,0,0,0,1
26655,46c706d6-6aef,210000,1,2,1,34,3,2,2,2,...,0,0,0,0,1,university,0,0,0,1
26656,4849f25c-3f1f,10000,1,3,1,43,0,0,0,-2,...,0,0,0,0,0,high school,0,1,0,0
26657,62c53ee3-f0cf,100000,1,1,2,38,0,-1,-1,0,...,4000,3000,2000,2000,0,graduate school,1,0,0,0
26658,67697c15-2247,80000,1,2,2,34,2,2,2,2,...,0,7000,0,4000,1,university,0,0,0,1
26659,ecff42d0-bdc6,220000,1,3,1,39,0,0,0,0,...,5003,3047,5000,1000,0,high school,0,1,0,0
26660,99d1fa0e-222b,150000,1,3,2,43,-1,-1,-1,-1,...,8998,129,0,0,0,high school,0,1,0,0
26661,95cdd3e7-4f24,30000,1,2,2,37,4,3,2,-1,...,22000,4200,2000,3100,1,university,0,0,0,1
26662,00d03f02-04cd,80000,1,3,1,41,1,-1,0,0,...,1178,1926,52964,1804,1,high school,0,1,0,0
26663,15d69f9f-5ad3,50000,1,2,1,46,0,0,0,0,...,1430,1000,1000,1000,1,university,0,0,0,1

In [27]:
df.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month,graduate school,high school,others,university
count,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,...,2.666400e+04,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000,26664.000000
mean,167919.054905,1.603060,1.842334,1.556031,35.505213,-0.017777,-0.133363,-0.167679,-0.225023,-0.269764,...,5.881110e+03,5259.514964,4887.048717,4843.729973,5257.843047,0.221797,0.352985,0.164266,0.015527,0.467222
std,129839.453081,0.489272,0.744661,0.521463,9.227442,1.126769,1.198640,1.199165,1.167897,1.131735,...,2.121431e+04,17265.439561,15956.349371,15311.721795,17635.468185,0.415463,0.477907,0.370524,0.123637,0.498934
min,10000.000000,1.000000,1.000000,1.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,8.020000e+02,390.000000,294.750000,242.750000,111.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.007000e+03,1822.000000,1500.000000,1500.000000,1500.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000e+03,4556.250000,4050.500000,4082.750000,4015.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,800000.000000,2.000000,4.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,8.000000,...,1.227082e+06,889043.000000,621000.000000,426529.000000,528666.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [38]:
df.corr()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month,graduate school,high school,others,university
LIMIT_BAL,1.000000,0.027046,-0.232688,-0.111873,0.149157,-0.273396,-0.296471,-0.286613,-0.269296,-0.249555,...,0.188049,0.207638,0.202795,0.218082,0.221305,-0.154423,0.260582,-0.139678,0.012190,-0.148892
SEX,0.027046,1.000000,0.014336,-0.031307,-0.088421,-0.058993,-0.070828,-0.067869,-0.060820,-0.055418,...,-0.002285,-0.011542,-0.000199,0.000081,-0.003342,-0.039945,-0.022777,-0.005669,0.007646,0.024133
EDUCATION,-0.232688,0.014336,1.000000,-0.137097,0.179035,0.112653,0.129558,0.124114,0.118464,0.105290,...,-0.033610,-0.042349,-0.039319,-0.044946,-0.046859,0.034966,-0.835517,0.689244,0.363889,0.198278
MARRIAGE,-0.111873,-0.031307,-0.137097,1.000000,-0.412828,0.019759,0.025096,0.034308,0.033082,0.036830,...,-0.007548,-0.003408,-0.014387,-0.000410,-0.009461,-0.026030,0.137198,-0.092283,-0.009422,-0.060549
AGE,0.149157,-0.088421,0.179035,-0.412828,1.000000,-0.044277,-0.054053,-0.055795,-0.054972,-0.059438,...,0.025421,0.029876,0.025307,0.020541,0.021640,0.014334,-0.096956,0.229301,0.008181,-0.079443
PAY_1,-0.273396,-0.058993,0.112653,0.019759,-0.044277,1.000000,0.675430,0.575617,0.539238,0.509140,...,-0.073295,-0.072682,-0.064112,-0.057021,-0.061031,0.325365,-0.142688,0.059008,-0.024941,0.099034
PAY_2,-0.296471,-0.070828,0.129558,0.025096,-0.054053,0.675430,1.000000,0.764960,0.659844,0.620211,...,-0.059088,-0.057972,-0.047047,-0.035798,-0.038711,0.263649,-0.169756,0.063009,-0.032340,0.123824
PAY_3,-0.286613,-0.067869,0.124114,0.034308,-0.055795,0.575617,0.764960,1.000000,0.776238,0.686325,...,-0.071311,-0.055098,-0.046136,-0.035672,-0.038332,0.238085,-0.161372,0.063176,-0.032780,0.115777
PAY_4,-0.269296,-0.060820,0.118464,0.033082,-0.054972,0.539238,0.659844,0.776238,1.000000,0.820401,...,-0.003546,-0.070528,-0.044948,-0.034297,-0.030607,0.219889,-0.154019,0.058468,-0.028530,0.111178
PAY_5,-0.249555,-0.055418,0.105290,0.036830,-0.059438,0.509140,0.620211,0.686325,0.820401,1.000000,...,-0.001857,0.010085,-0.057446,-0.033770,-0.026060,0.204948,-0.139655,0.049600,-0.027157,0.103665
PAY_6,-0.236037,-0.043668,0.088835,0.033366,-0.053532,0.475740,0.574122,0.632940,0.715778,0.815597,...,-0.005085,0.005841,0.019515,-0.048457,-0.026136,0.190182,-0.124982,0.041350,-0.035988,0.097925
BILL_AMT1,0.287009,-0.032336,0.016156,-0.028610,0.056245,0.185826,0.233781,0.207819,0.202165,0.206113,...,0.112460,0.145635,0.160204,0.163425,0.178943,-0.020508,-0.024230,-0.022465,0.035485,0.031099
BILL_AMT2,0.279289,-0.029682,0.012307,-0.026009,0.054099,0.188799,0.234120,0.237636,0.225881,0.227525,...,0.114473,0.137514,0.148685,0.153851,0.172472,-0.014579,-0.021386,-0.022517,0.029468,0.029904
BILL_AMT3,0.285299,-0.023217,0.007683,-0.029192,0.054107,0.181257,0.226327,0.229639,0.247123,0.247091,...,0.287837,0.119456,0.141010,0.159446,0.178121,-0.014649,-0.014513,-0.022361,0.028593,0.023422
BILL_AMT4,0.294342,-0.019970,-0.005862,-0.027740,0.051241,0.178812,0.221877,0.227038,0.245354,0.272785,...,0.217716,0.293652,0.131700,0.158633,0.171339,-0.011349,-0.004295,-0.030887,0.020328,0.022014
BILL_AMT5,0.295198,-0.015168,-0.013174,-0.029895,0.049701,0.180438,0.220758,0.224623,0.241584,0.270335,...,0.189566,0.241291,0.296192,0.140669,0.161847,-0.006753,0.000790,-0.031975,0.009766,0.020569
BILL_AMT6,0.289818,-0.014406,-0.012670,-0.024414,0.047519,0.177486,0.219289,0.221822,0.237721,0.262737,...,0.167941,0.219008,0.251668,0.305627,0.117253,-0.006274,-0.003394,-0.030759,0.001374,0.025753
PAY_AMT1,0.194820,0.002964,-0.040092,-0.002951,0.025437,-0.081450,-0.083251,0.000774,-0.011479,-0.008093,...,0.326951,0.268781,0.204178,0.154208,0.192774,-0.072431,0.048126,-0.022010,0.005257,-0.031055
PAY_AMT2,0.188049,-0.002285,-0.033610,-0.007548,0.025421,-0.073295,-0.059088,-0.071311,-0.003546,-0.001857,...,1.000000,0.265713,0.188660,0.136844,0.164655,-0.061555,0.046784,-0.017001,0.014680,-0.035825
PAY_AMT3,0.207638,-0.011542,-0.042349,-0.003408,0.029876,-0.072682,-0.057972,-0.055098,-0.070528,0.010085,...,0.265713,1.000000,0.222513,0.158325,0.163026,-0.058010,0.054917,-0.030985,0.025035,-0.035795
PAY_AMT4,0.202795,-0.000199,-0.039319,-0.014387,0.025307,-0.064112,-0.047047,-0.046136,-0.044948,-0.057446,...,0.188660,0.222513,1.000000,0.153347,0.165131,-0.054572,0.043595,-0.023582,0.001186,-0.024539
PAY_AMT5,0.218082,0.000081,-0.044946,-0.000410,0.020541,-0.057021,-0.035798,-0.035672,-0.034297,-0.033770,...,0.136844,0.158325,0.153347,1.000000,0.158727,-0.056651,0.046328,-0.033544,0.004448,-0.020567
PAY_AMT6,0.221305,-0.003342,-0.046859,-0.009461,0.021640,-0.061031,-0.038711,-0.038332,-0.030607,-0.026060,...,0.164655,0.163026,0.165131,0.158727,1.000000,-0.054838,0.052861,-0.036246,0.015362,-0.027522
default payment next month,-0.154423,-0.039945,0.034966,-0.026030,0.014334,0.325365,0.263649,0.238085,0.219889,0.204948,...,-0.061555,-0.058010,-0.054572,-0.056651,-0.054838,1.000000,-0.049595,0.035943,-0.044411,0.031817
graduate school,0.260582,-0.022777,-0.835517,0.137198,-0.096956,-0.142688,-0.169756,-0.161372,-0.154019,-0.139655,...,0.046784,0.054917,0.043595,0.046328,0.052861,-0.049595,1.000000,-0.327463,-0.092759,-0.691687
high school,-0.139678,-0.005669,0.689244,-0.092283,0.229301,0.059008,0.063009,0.063176,0.058468,0.049600,...,-0.017001,-0.030985,-0.023582,-0.033544,-0.036246,0.035943,-0.327463,1.000000,-0.055677,-0.415173
others,0.012190,0.007646,0.363889,-0.009422,0.008181,-0.024941,-0.032340,-0.032780,-0.028530,-0.027157,...,0.014680,0.025035,0.001186,0.004448,0.015362,-0.044411,-0.092759,-0.055677,1.000000,-0.117604
university,-0.148892,0.024133,0.198278,-0.060549,-0.079443,0.099034,0.123824,0.115777,0.111178,0.103665,...,-0.035825,-0.035795,-0.024539,-0.020567,-0.027522,0.031817,-0.691687,-0.415173,-0.117604,1.000000